name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This helps us improve Story UI for everyone.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Story UI does X when it should do Y..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter prompt '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Your development environment
      placeholder: |
        - OS: [e.g. macOS 14.0]
        - Node.js: [e.g. 18.17.0]
        - Story UI version: [e.g. 1.5.2]
        - Storybook version: [e.g. 7.6.0]
        - Design system: [e.g. Ant Design 5.0]
        - Browser: [e.g. Chrome 120]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: Any relevant error messages or console output
      render: shell
      placeholder: "Paste error logs here..."

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: Screenshots, config files, or other context
      placeholder: "Add any other context about the problem here..."
