/**
 * Story artifacts — a story is a FILE SET, not a single file.
 *
 * Inline `style={{}}` cannot express `:hover`, `:focus-visible` or
 * `[data-active]`, so any composition with real interaction states needs a
 * stylesheet next to it. That makes emission multi-file.
 *
 * The hazard is deletion. Story files are removed from nineteen different call
 * sites across the server, the stdio server, the panel routes and the CLI. If
 * even one of them removes a `.stories.tsx` without its sibling, an orphaned
 * `.module.css` is left in the user's repository forever.
 *
 * Rather than require all nineteen to be correct, artifacts are:
 *   - named deterministically from the story's own base name, and
 *   - swept: any generated stylesheet with no matching story is removed on the
 *     next listing or reconcile.
 *
 * So a delete path that knows nothing about stylesheets still converges to a
 * clean directory.
 */

import fs from 'fs';
import path from 'path';
import { logger } from './logger.js';

/** Marker proving a stylesheet is ours, so a sweep can never touch a hand-written one. */
export const GENERATED_CSS_MARKER = '/* Generated by Story UI — do not edit by hand. */';

/**
 * A story file name the server will accept from a client.
 *
 * Every other write route confines its path with a base-directory check; the
 * generation routes were the one place a client-supplied `fileName` reached
 * `path.join` untouched, so `../../.storybook/preview.tsx` was a valid target
 * for model output. The rule is stricter than "stays inside the directory":
 * a story is a single file in the generated directory, so the name must be a
 * bare basename with a story extension. Nothing else is a story.
 */
export function isSafeStoryFileName(fileName: unknown): fileName is string {
  if (typeof fileName !== 'string' || fileName.length === 0 || fileName.length > 200) return false;
  if (fileName !== path.basename(fileName)) return false;
  if (fileName.startsWith('.') || fileName.includes('\\') || fileName.includes('\0')) return false;
  // Either a bare stem (the pipeline appends the framework's extension) or a
  // complete story name. Any other extension is not a story.
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(fileName)) return false;
  if (!fileName.includes('.')) return true;
  return /\.stories\.(tsx|ts|jsx|js|vue|svelte|mdx)$/.test(fileName);
}

export class UnsafeStoryFileNameError extends Error {
  constructor(fileName: unknown) {
    super(`Refusing to write "${String(fileName)}": a story file name must be a bare name ending in .stories.<ext>`);
    this.name = 'UnsafeStoryFileNameError';
  }
}

/** The placeholder import the model is told to write, before we know the hash. */
export const CSS_IMPORT_PLACEHOLDER = './styles.module.css';

const STORY_EXTENSIONS = ['.stories.tsx', '.stories.ts', '.stories.jsx', '.stories.js', '.stories.svelte'];

/** "pricing-card-a1b2.stories.tsx" -> "pricing-card-a1b2" */
export function storyBaseName(fileName: string): string {
  for (const ext of STORY_EXTENSIONS) {
    if (fileName.endsWith(ext)) return fileName.slice(0, -ext.length);
  }
  return fileName.replace(/\.[^.]+$/, '');
}

/** Stylesheet filename that belongs to a given story file. */
export function stylesheetNameFor(storyFileName: string): string {
  return `${storyBaseName(storyFileName)}.module.css`;
}

export interface WrittenArtifacts {
  storyPath: string;
  stylesheetPath?: string;
}

/**
 * Repoint the placeholder stylesheet specifier at the real sibling file.
 *
 * Only rewrites it where it appears as a module specifier — `import … from
 * '…'`, a bare `import '…'`, or `require('…')`. String literals elsewhere in
 * the story are the user's content and must survive untouched.
 */
export function rewriteStylesheetImport(code: string, target: string): string {
  const spec = CSS_IMPORT_PLACEHOLDER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return code
    // import x from './styles.module.css'  |  import './styles.module.css'
    .replace(
      new RegExp(`(\\bimport\\b[^;\\n]*?['"])${spec}(['"])`, 'g'),
      (_m, pre, post) => `${pre}${target}${post}`,
    )
    // require('./styles.module.css')
    .replace(
      new RegExp(`(\\brequire\\s*\\(\\s*['"])${spec}(['"]\\s*\\))`, 'g'),
      (_m, pre, post) => `${pre}${target}${post}`,
    );
}

/**
 * Write a story and, when present, its stylesheet.
 *
 * The model cannot know the hashed filename, so it is told to import
 * `./styles.module.css`; that import is rewritten here to the real sibling.
 */
export function writeStoryArtifacts(args: {
  dir: string;
  fileName: string;
  code: string;
  css?: string | null;
}): WrittenArtifacts {
  const { dir, fileName, css } = args;
  let { code } = args;

  // Defence in depth: the routes validate too, but this is the write.
  if (!isSafeStoryFileName(fileName)) throw new UnsafeStoryFileNameError(fileName);
  fs.mkdirSync(dir, { recursive: true });
  const storyPath = path.join(dir, fileName);

  if (css && css.trim()) {
    const cssName = stylesheetNameFor(fileName);
    // Point the placeholder import at the real sibling.
    //
    // Scoped to actual import/require statements rather than a blind string
    // replace: a generated story about files legitimately contained
    // `{ name: 'styles.module.css' }` as sample data, and a global replace would
    // silently rewrite the user's content.
    code = rewriteStylesheetImport(code, `./${cssName}`);

    const cssPath = path.join(dir, cssName);
    const body = css.trim().startsWith(GENERATED_CSS_MARKER)
      ? css.trim()
      : `${GENERATED_CSS_MARKER}\n${css.trim()}\n`;
    fs.writeFileSync(cssPath, body, 'utf-8');
    fs.writeFileSync(storyPath, code, 'utf-8');
    logger.log(`🎨 Wrote stylesheet ${cssName}`);
    return { storyPath, stylesheetPath: cssPath };
  }

  // No stylesheet this time. Remove a stale one from a previous revision of the
  // same story, or the import would resolve to dead rules.
  const staleCss = path.join(dir, stylesheetNameFor(fileName));
  if (fs.existsSync(staleCss) && isGeneratedStylesheet(staleCss)) {
    try { fs.unlinkSync(staleCss); } catch { /* best effort */ }
  }

  fs.writeFileSync(storyPath, code, 'utf-8');
  return { storyPath };
}

/** Only files we wrote carry the marker; never delete a hand-authored stylesheet. */
export function isGeneratedStylesheet(filePath: string): boolean {
  try {
    return fs.readFileSync(filePath, 'utf-8').startsWith(GENERATED_CSS_MARKER);
  } catch {
    return false;
  }
}

/**
 * Remove the stylesheet belonging to a story. Safe to call from any delete path,
 * including ones that have already removed the story file.
 */
export function removeStoryArtifacts(storyFilePath: string): void {
  try {
    const dir = path.dirname(storyFilePath);
    const cssPath = path.join(dir, stylesheetNameFor(path.basename(storyFilePath)));
    if (fs.existsSync(cssPath) && isGeneratedStylesheet(cssPath)) {
      fs.unlinkSync(cssPath);
    }
  } catch {
    // Deletion is best-effort; the sweep below is the real guarantee.
  }
}

/**
 * Remove generated stylesheets whose story no longer exists.
 *
 * This is what makes the nineteen existing delete call sites safe without
 * modifying them: whichever path removed the story, the orphan is collected on
 * the next listing or reconcile.
 */
export function sweepOrphanedArtifacts(dir: string): number {
  let removed = 0;
  try {
    if (!fs.existsSync(dir)) return 0;
    const entries = fs.readdirSync(dir);
    const stories = new Set(entries.filter(f => STORY_EXTENSIONS.some(e => f.endsWith(e))).map(storyBaseName));

    for (const entry of entries) {
      if (!entry.endsWith('.module.css')) continue;
      const base = entry.slice(0, -'.module.css'.length);
      if (stories.has(base)) continue;
      const full = path.join(dir, entry);
      if (!isGeneratedStylesheet(full)) continue; // hand-written — leave it alone
      try {
        fs.unlinkSync(full);
        removed++;
      } catch { /* best effort */ }
    }
    if (removed > 0) {
      logger.log(`🧹 Removed ${removed} orphaned generated stylesheet(s)`);
    }
  } catch {
    // Never let housekeeping break a request.
  }
  return removed;
}

/**
 * Split a model response into story code and an optional stylesheet.
 *
 * The story is extracted upstream by the framework-aware extractor; this only
 * looks for a fenced css block, and ignores one that was not actually used by
 * the story (a stylesheet nothing imports is noise in the user's repo).
 */
export function extractStylesheet(response: string, storyCode: string): string | null {
  if (!storyCode.includes(CSS_IMPORT_PLACEHOLDER) && !/\.module\.css/.test(storyCode)) {
    return null;
  }
  const match = response.match(/```(?:css|scss)\s*\n([\s\S]*?)```/);
  if (!match) return null;
  const css = match[1].trim();
  return css.length > 0 ? css : null;
}

/**
 * A title as the file declares it carries the story prefix (`Generated/Data
 * Table`); a title as the user typed it does not. Clients send either, and an
 * id derived from the prefixed form (`generated-data-table--default`) matches
 * nothing in Storybook's index, so the update verified against a story that
 * did not exist. One form, always.
 */
export function stripStoryPrefix(title: string, prefix: string | undefined): string {
  const p = (prefix || '').replace(/\/+$/, '');
  if (!p) return title.trim();
  const t = title.trim();
  return t.toLowerCase().startsWith(`${p.toLowerCase()}/`) ? t.slice(p.length + 1).trim() : t;
}
