/**
 * Story UI — Storybook manager addon.
 *
 * Two jobs:
 *
 * 1. An "Edit in Story UI" toolbar button that appears when viewing a story
 *    generated by Story UI (title under the "Generated/" prefix). Clicking it
 *    stashes the story's component id in sessionStorage (shared same-origin
 *    with the preview iframe) and navigates to the Story UI panel, which picks
 *    up the stash and opens that story's chat conversation.
 *
 *    Targets the V2 workspace when the project has one, falling back to the
 *    V1 panel otherwise. It used to be hardcoded to V1, so on a V2 project
 *    this button silently threw the user back into the old generator with
 *    none of their conversation — the single most visible leftover of V1.
 *
 * 2. Focus mode for the workspace. The workspace is an application living in
 *    Storybook's docs preview, and Storybook's sidebar takes ~300px of it and
 *    the addons panel another strip. While the workspace docs entry is the
 *    active story, both are folded away, and put back exactly as they were
 *    when the user navigates anywhere else. The workspace's own "Focus"
 *    button toggles it (a postMessage from the preview frame), and the
 *    preference is remembered in localStorage under `story-ui-focus` — which
 *    the preview frame shares, being same-origin.
 *
 * Wired up from .storybook/manager.ts(x):
 *   import '../src/stories/StoryUI/manager';
 *
 * Requires Storybook 9+ (the consolidated `storybook/manager-api` package).
 */
import React from 'react';
import { addons, types, useStorybookApi, useStorybookState } from 'storybook/manager-api';

const EDIT_REQUEST_KEY = 'story-ui-edit-request';
/**
 * The `<Meta title>` in StoryUIV2.mdx. The docs id is looked up from
 * Storybook's index by this title (see useStoryUiTarget), so the id
 * derivation rule never has to be reproduced here; WORKSPACE_DOCS_ID is the
 * fallback for the moment before the index has answered, and is what that
 * title indexes as under Storybook's current rule.
 */
const WORKSPACE_TITLE = 'Story UI/Workspace';
const WORKSPACE_DOCS_ID = 'story-ui-workspace--docs';
const PANEL_DOCS_ID = 'story-ui-story-generator--docs';
/** V2 first; V1 is the fallback for projects that never adopted the workspace. */
const TARGET_IDS = [WORKSPACE_DOCS_ID, PANEL_DOCS_ID];
const GENERATED_PREFIX = 'Generated/';

/** localStorage key for the focus preference; "false" is the only opt-out. */
const FOCUS_KEY = 'story-ui-focus';
/** postMessage types, preview → manager and manager → preview. */
const FOCUS_MESSAGE = 'story-ui:focus';
const FOCUS_STATE_MESSAGE = 'story-ui:focus-state';

interface StoryUiTargets {
  /** The surface "Edit in Story UI" opens. */
  target: string;
  /** The workspace docs entry's real id, when the project has one. */
  workspaceId: string | null;
}

/**
 * Which Story UI surface this project actually has.
 *
 * Read from Storybook's own index rather than the manager API: `api.getData`
 * varies across Storybook versions and returned nothing here, so a V2 project
 * silently fell back to the V1 panel — the button threw the user into the old
 * generator with none of their conversation. /index.json is same-origin,
 * version-proof, and the check every other part of Story UI already uses.
 *
 * The workspace id is found by TITLE, which is what the MDX declares; the
 * index is the one place Storybook states what that title became.
 */
function useStoryUiTarget(): StoryUiTargets {
  const [targets, setTargets] = React.useState<StoryUiTargets>({ target: PANEL_DOCS_ID, workspaceId: null });
  React.useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch('index.json');
        if (!res.ok) return;
        const entries: Record<string, any> = (await res.json())?.entries ?? {};
        const byTitle = Object.values(entries).find(
          (e: any) => e?.type === 'docs' && e?.title === WORKSPACE_TITLE,
        ) as { id?: string } | undefined;
        const workspaceId = byTitle?.id ?? (entries[WORKSPACE_DOCS_ID] ? WORKSPACE_DOCS_ID : null);
        const found = workspaceId ?? TARGET_IDS.find(id => entries[id]);
        if (!cancelled) setTargets({ target: found ?? PANEL_DOCS_ID, workspaceId });
      } catch {
        /* keep the V1 default, which every project has */
      }
    })();
    return () => { cancelled = true; };
  }, []);
  return targets;
}

const readFocusPreference = (): boolean => {
  try { return localStorage.getItem(FOCUS_KEY) !== 'false'; } catch { return true; }
};

const writeFocusPreference = (on: boolean) => {
  try { localStorage.setItem(FOCUS_KEY, on ? 'true' : 'false'); } catch { /* private mode */ }
};

/** Tell the workspace what the chrome is actually doing, so its button agrees. */
const postFocusState = (on: boolean) => {
  try {
    const frame = document.getElementById('storybook-preview-iframe') as HTMLIFrameElement | null;
    frame?.contentWindow?.postMessage({ type: FOCUS_STATE_MESSAGE, on }, window.location.origin);
  } catch { /* no preview frame yet */ }
};

/**
 * Fold Storybook's sidebar and addons panel away while the workspace is the
 * active story, and restore them on the way out.
 *
 * `toggleNav(false)` / `togglePanel(false)`, not `setOptions({ showNav })`:
 * in Storybook 10 the layout state no longer has `showNav`/`showPanel` at
 * all — visibility IS `navSize > 0` and the panel's size > 0 — so setOptions
 * with those keys is a silent no-op, while the toggles are the real setters
 * (and persist per session only, so nothing leaks into the user's saved
 * layout). `getIsNavShown` / `getIsPanelShown` read the same truth, which is
 * what makes the restore exact rather than "show everything".
 */
function useWorkspaceFocus(api: ReturnType<typeof useStorybookApi>, storyId: string, workspaceId: string | null) {
  const [wanted, setWanted] = React.useState<boolean>(readFocusPreference);
  const saved = React.useRef<{ nav: boolean; panel: boolean } | null>(null);

  // The workspace's Focus button, from inside the preview frame.
  React.useEffect(() => {
    const onMessage = (e: MessageEvent) => {
      if (e.origin !== window.location.origin) return;
      const msg = e.data;
      if (!msg || msg.type !== FOCUS_MESSAGE || typeof msg.on !== 'boolean') return;
      writeFocusPreference(msg.on);
      setWanted(msg.on);
    };
    window.addEventListener('message', onMessage);
    return () => window.removeEventListener('message', onMessage);
  }, []);

  const onWorkspace = !!workspaceId && storyId === workspaceId;
  const focus = onWorkspace && wanted;

  React.useEffect(() => {
    const canToggle = typeof api?.toggleNav === 'function' && typeof api?.togglePanel === 'function';
    if (!canToggle) return;
    if (focus) {
      if (!saved.current) {
        saved.current = {
          nav: typeof api.getIsNavShown === 'function' ? api.getIsNavShown() : true,
          panel: typeof api.getIsPanelShown === 'function' ? api.getIsPanelShown() : true,
        };
      }
      api.toggleNav(false);
      api.togglePanel(false);
      postFocusState(true);
      return;
    }
    if (saved.current) {
      api.toggleNav(saved.current.nav);
      api.togglePanel(saved.current.panel);
      saved.current = null;
    }
    if (onWorkspace) postFocusState(false);
  }, [api, focus, onWorkspace]);

  // Leaving the manager entirely (the tool unmounts) must not strand the user
  // without a sidebar.
  React.useEffect(() => () => {
    if (saved.current && typeof api?.toggleNav === 'function') {
      api.toggleNav(saved.current.nav);
      api.togglePanel(saved.current.panel);
      saved.current = null;
    }
  }, [api]);
}

const EditInStoryUITool: React.FC = () => {
  const api = useStorybookApi();
  // Subscribing to manager state re-renders the tool on story navigation.
  useStorybookState();
  const { target, workspaceId } = useStoryUiTarget();

  const current = api.getCurrentStoryData?.();
  const title: string = (current as any)?.title ?? '';
  const storyId: string = (current as any)?.id ?? '';

  useWorkspaceFocus(api, storyId, workspaceId);

  if (!storyId || TARGET_IDS.includes(storyId) || storyId === workspaceId || !title.startsWith(GENERATED_PREFIX)) {
    return null;
  }


  const openInPanel = () => {
    try {
      sessionStorage.setItem(
        EDIT_REQUEST_KEY,
        JSON.stringify({ componentId: storyId.split('--')[0], title })
      );
    } catch {
      /* sessionStorage unavailable — panel just opens without preselection */
    }
    try {
      api.selectStory(target);
    } catch {
      window.location.search = `?path=/docs/${target.replace('--docs', '')}--docs`;
    }
  };

  return (
    <button
      onClick={openInPanel}
      title="Open this story's chat in Story UI"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        height: 28,
        padding: '0 10px',
        margin: '2px 0',
        border: 0,
        borderRadius: 4,
        background: 'transparent',
        color: 'inherit',
        font: 'inherit',
        fontSize: 12,
        fontWeight: 700,
        cursor: 'pointer',
      }}
      onMouseEnter={e => { e.currentTarget.style.background = 'rgba(2, 156, 253, 0.12)'; }}
      onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; }}
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M12 20h9" />
        <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4Z" />
      </svg>
      Edit in Story UI
    </button>
  );
};

addons.register('story-ui', () => {
  addons.add('story-ui/edit-tool', {
    type: types.TOOL,
    title: 'Edit in Story UI',
    match: ({ viewMode }) => viewMode === 'story' || viewMode === 'docs',
    render: () => <EditInStoryUITool />,
  });
});
