/**
 * Story UI — Storybook manager addon.
 *
 * Adds an "Edit in Story UI" toolbar button that appears when viewing a
 * story generated by Story UI (title under the "Generated/" prefix). Clicking
 * it stashes the story's component id in sessionStorage (shared same-origin
 * with the preview iframe) and navigates to the Story UI panel, which picks
 * up the stash and opens that story's chat conversation.
 *
 * Targets the V2 workspace when the project has one, falling back to the V1
 * panel otherwise. It used to be hardcoded to V1, so on a V2 project this
 * button silently threw the user back into the old generator with none of
 * their conversation — the single most visible leftover of V1.
 *
 * Wired up from .storybook/manager.ts(x):
 *   import '../src/stories/StoryUI/manager';
 *
 * Requires Storybook 9+ (the consolidated `storybook/manager-api` package).
 */
import React from 'react';
import { addons, types, useStorybookApi, useStorybookState } from 'storybook/manager-api';

const EDIT_REQUEST_KEY = 'story-ui-edit-request';
const WORKSPACE_DOCS_ID = 'story-ui-workspace--docs';
const PANEL_DOCS_ID = 'story-ui-story-generator--docs';
/** V2 first; V1 is the fallback for projects that never adopted the workspace. */
const TARGET_IDS = [WORKSPACE_DOCS_ID, PANEL_DOCS_ID];
const GENERATED_PREFIX = 'Generated/';

/**
 * Which Story UI surface this project actually has.
 *
 * Read from Storybook's own index rather than the manager API: `api.getData`
 * varies across Storybook versions and returned nothing here, so a V2 project
 * silently fell back to the V1 panel — the button threw the user into the old
 * generator with none of their conversation. /index.json is same-origin,
 * version-proof, and the check every other part of Story UI already uses.
 */
function useStoryUiTarget(): string {
  const [target, setTarget] = React.useState(PANEL_DOCS_ID);
  React.useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch('index.json');
        if (!res.ok) return;
        const entries = (await res.json())?.entries ?? {};
        const found = TARGET_IDS.find(id => entries[id]);
        if (found && !cancelled) setTarget(found);
      } catch {
        /* keep the V1 default, which every project has */
      }
    })();
    return () => { cancelled = true; };
  }, []);
  return target;
}

const EditInStoryUITool: React.FC = () => {
  const api = useStorybookApi();
  // Subscribing to manager state re-renders the tool on story navigation.
  useStorybookState();
  const target = useStoryUiTarget();

  const current = api.getCurrentStoryData?.();
  const title: string = (current as any)?.title ?? '';
  const storyId: string = (current as any)?.id ?? '';

  if (!storyId || TARGET_IDS.includes(storyId) || !title.startsWith(GENERATED_PREFIX)) {
    return null;
  }


  const openInPanel = () => {
    try {
      sessionStorage.setItem(
        EDIT_REQUEST_KEY,
        JSON.stringify({ componentId: storyId.split('--')[0], title })
      );
    } catch {
      /* sessionStorage unavailable — panel just opens without preselection */
    }
    try {
      api.selectStory(target);
    } catch {
      window.location.search = `?path=/docs/${target.replace('--docs', '')}--docs`;
    }
  };

  return (
    <button
      onClick={openInPanel}
      title="Open this story's chat in Story UI"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        height: 28,
        padding: '0 10px',
        margin: '2px 0',
        border: 0,
        borderRadius: 4,
        background: 'transparent',
        color: 'inherit',
        font: 'inherit',
        fontSize: 12,
        fontWeight: 700,
        cursor: 'pointer',
      }}
      onMouseEnter={e => { e.currentTarget.style.background = 'rgba(2, 156, 253, 0.12)'; }}
      onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; }}
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M12 20h9" />
        <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4Z" />
      </svg>
      Edit in Story UI
    </button>
  );
};

addons.register('story-ui', () => {
  addons.add('story-ui/edit-tool', {
    type: types.TOOL,
    title: 'Edit in Story UI',
    match: ({ viewMode }) => viewMode === 'story' || viewMode === 'docs',
    render: () => <EditInStoryUITool />,
  });
});
