/**
 * Story UI — Storybook manager addon.
 *
 * Adds an "Edit in Story UI" toolbar button that appears when viewing a
 * story generated by Story UI (title under the "Generated/" prefix). Clicking
 * it stashes the story's component id in sessionStorage (shared same-origin
 * with the preview iframe) and navigates to the Story UI panel, which picks
 * up the stash and opens that story's chat conversation.
 *
 * Wired up from .storybook/manager.ts(x):
 *   import '../src/stories/StoryUI/manager';
 *
 * Requires Storybook 9+ (the consolidated `storybook/manager-api` package).
 */
import React from 'react';
import { addons, types, useStorybookApi, useStorybookState } from 'storybook/manager-api';

const EDIT_REQUEST_KEY = 'story-ui-edit-request';
const PANEL_DOCS_ID = 'story-ui-story-generator--docs';
const GENERATED_PREFIX = 'Generated/';

const EditInStoryUITool: React.FC = () => {
  const api = useStorybookApi();
  // Subscribing to manager state re-renders the tool on story navigation.
  useStorybookState();

  const current = api.getCurrentStoryData?.();
  const title: string = (current as any)?.title ?? '';
  const storyId: string = (current as any)?.id ?? '';

  if (!storyId || storyId === PANEL_DOCS_ID || !title.startsWith(GENERATED_PREFIX)) {
    return null;
  }

  const openInPanel = () => {
    try {
      sessionStorage.setItem(
        EDIT_REQUEST_KEY,
        JSON.stringify({ componentId: storyId.split('--')[0], title })
      );
    } catch {
      /* sessionStorage unavailable — panel just opens without preselection */
    }
    try {
      api.selectStory(PANEL_DOCS_ID);
    } catch {
      window.location.search = `?path=/docs/${PANEL_DOCS_ID.replace('--docs', '')}--docs`;
    }
  };

  return (
    <button
      onClick={openInPanel}
      title="Open this story's chat in Story UI"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        height: 28,
        padding: '0 10px',
        margin: '2px 0',
        border: 0,
        borderRadius: 4,
        background: 'transparent',
        color: 'inherit',
        font: 'inherit',
        fontSize: 12,
        fontWeight: 700,
        cursor: 'pointer',
      }}
      onMouseEnter={e => { e.currentTarget.style.background = 'rgba(2, 156, 253, 0.12)'; }}
      onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; }}
    >
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M12 20h9" />
        <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4Z" />
      </svg>
      Edit in Story UI
    </button>
  );
};

addons.register('story-ui', () => {
  addons.add('story-ui/edit-tool', {
    type: types.TOOL,
    title: 'Edit in Story UI',
    match: ({ viewMode }) => viewMode === 'story' || viewMode === 'docs',
    render: () => <EditInStoryUITool />,
  });
});
